#! /bin/bash

### BEGIN INIT INFO
# Provides:          zartan_resque_pool
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the resque pool manager
# Description:       starts the resque pool manager
### END INIT INFO

ZARTAN_ROOT=/var/www/zartan
USER=zartan

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/$USER/.rvm/wrappers/ruby-2.2.0/

DAEMON=bundle

PID=$ZARTAN_ROOT/shared/pids/resque_pool.pid
DAEMON_OPTS="exec resque-pool --config $ZARTAN_ROOT/current/config/resque_pool.yml --environment production --daemon --pidfile $PID --stdout $ZARTAN_ROOT/shared/log/resque_pool.stdout.log --stderr $ZARTAN_ROOT/shared/log/resque_pool.stderr.log"

NAME=zartan_resque_pool
DESC=resque_pool

cd $ZARTAN_ROOT/current
case "$1" in
  start)
    echo -n "Starting $DESC: "
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
  ;;
  stop)
    echo -n "Stopping $DESC: "
    kill -QUIT `cat $PID`
    echo "$NAME."
  ;;
  restart)
    echo -n "Restarting $DESC: "
    kill -QUIT `cat $PID`
    while [[ -e $PID ]]; do true; done
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
  ;;
  reload)
    echo -n "Reloading $DESC configuration: "
    kill -HUP `cat $PID`
    echo "$NAME."
  ;;
  *)
    echo "Usage: $NAME {start|stop|restart|reload}" >&2
    exit 1
  ;;
esac
cd -

exit 0

