#! /bin/bash

### BEGIN INIT INFO
# Provides:          zartan_unicorn
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts zartan's unicorn web server
# Description:       starts zartan's unicorn
### END INIT INFO

ZARTAN_ROOT=/var/www/zartan
USER=zartan

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/$USER/.rvm/wrappers/ruby-2.2.0@zartan

DAEMON=bundle

DAEMON_OPTS="exec unicorn -c $ZARTAN_ROOT/current/config/unicorn.rb -E production -D"

NAME=zartan_unicorn
DESC=unicorn
PID=$ZARTAN_ROOT/shared/pids/unicorn.pid

cd $ZARTAN_ROOT/current
case "$1" in
  start)
    echo -n "Starting $DESC: "
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
  ;;
  stop)
    echo -n "Stopping $DESC: "
    kill -QUIT `cat $PID`
    echo "$NAME."
  ;;
  restart)
    echo -n "Restarting $DESC: "
    OLDPID=`cat $PID`
    kill -s USR2 $OLDPID
    NEWPID=`cat $PID 2>/dev/null`
    while [[ -n "$NEWPID" && "$OLDPID" == "$NEWPID" ]]; do NEWPID=`cat $PID 2>/dev/null`; done
    kill -QUIT $OLDPID
    echo "$NAME."
  ;;
  reload)
    echo -n "Reloading $DESC configuration: "
    kill -HUP `cat $PID`
    echo "$NAME."
  ;;
  *)
    echo "Usage: $NAME {start|stop|restart|reload}" >&2
    exit 1
  ;;
esac
cd -

exit 0


